name: release

on:
  push:
    paths-ignore: [".gitignore", "**/*.md"]
    branches: [master]

jobs:
  docker-publish-latest:
    if: github.repository_owner == 'FlagBrew'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: fmcore/flagbot
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS }}
  post-to-webhook:
    needs: [docker-publish-latest]
    runs-on: ubuntu-latest
    steps:
      - run: |
          set +x
          curl -XPOST -H 'X-Webhook-Auth: ${{ secrets.WEBHOOK_SECRET }}' -H "Content-type: application/json" -d '{"app": "flagbrew", "service": "flagbot"}' '${{ secrets.WEBHOOK_URL }}'
